### ISSUE TITLE
My first raspberry pi project :)

### ISSUE THREAD

**Issue by sameera207** [rails-oceania/roro#146]
This talk is about , as a newbie to `raspberry pi`, how I was able use my existing ruby/javascript knowledge to   automate my irrigation system 🌿💦

We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
**Proposal (I want to give this talk)**

- Intended audience (beginners, intermediates, advanced)
**All**

For proposals:
- Which month would you be ready for?
**Feb 13th** (next week)

- Is this a 5m (lightning) talk, or a 15m talk?
**15 mins**

**Comment by paulfioravanti** [comment]
Thanks @sameera207! You're locked in for February!

**Comment by sameera207** [comment]
thanks @paulfioravanti , 👍

**Comment by paulfioravanti** [comment]
Thanks for presenting, @sameera207, especially since it was at the last minute :).

If possible, would you be able to make your slides available publicly by exporting it to PDF, putting it on your slide-sharing service of choice (Speakerdeck, Slideshare, Slides etc...), and linking to it in the meetup comments (https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/nnvkcpyxdbrb/). If you plan on sharing them on Twitter, please tag `@rorosyd` so we can give you a retweet.

**Comment by sameera207** [comment]
hey @paulfioravanti , sure, however give me few days (bit stuck with work), I will come up with a way to make it more sense to the readers. 

Coz current slide set will not make any sense since in doesnt have the code samples etc... 

But once I have something , I'll upload and tweet :)
