### ISSUE TITLE
New features in Ruby 2.6

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#173]
There are a couple of headline items in the new Ruby 2.6 - endless ranges and `then`.

Could be fun to go over some worked examples in a lightening talk?

**Proposal or request:** I don't mind, I could do it - someone else could do it.
**Intended audience:** all

**Comment by paulfioravanti** [comment]
Hi @cyclotron3k, thanks for submitting your issues!  If, out of the ones you've submitted, there are ones that you would like someone else to do, rather than volunteer to do yourself, please mark them with a `sydney-presentation-request` label.

Personally, I think this talk would be a great one for you to do, as it would involve new information that you can research and then share with the community, and it would also potentially give you the chance to complement any presentation you do with demos using an IRB console with Ruby version 2.6-preview2 running.

If think it's fine to cover this content in either a full-length or lightning format, and at this stage we could slot you in for the August meetup for either of those formats, giving you two months to prepare (and keep tabs on other new Ruby 2.6 features that come out in the meantime).

If this is something you want to do and lock in a slot for, let us know and we'll attach a milestone to this issue. If August is too early, feel free to pick a month when you'd like to aim for.

Also, don't hesitate to let @RocketRobC or myself know if you would like any assistance with preparing your talk, or if you want someone to hear a dry run etc.

**Comment by cyclotron3k** [comment]
Perhaps it's worth delaying this one until 2.6 is an official release? Although, I assume there won't be many more significant changes.

I expect it would be a lightening talk. The performance improvements and the JIT compiler would be worth a mention, but apart from endless ranges and yield_self/then, I can't think of much else to talk about.
