### ISSUE TITLE
A Developer's Guide to Ergonomics

### ISSUE THREAD

**Issue by lis2** [rails-oceania/roro#182]
Ergonomic is a very important topic to keep us healthy and productive. I made some research about the recent recommendation in that area and I would like to present you a summary. 

Proposal or request: **Propsal**
Lightening or 15m: **7 minutes lightning**
Intended audience: **all**

**Comment by paulfioravanti** [comment]
Thanks, Krzysztof! As mentioned in other comms, since your talk is ready, we'll schedule you in for the October meetup, and as a backup lightning talk for August and September.

**Comment by paulfioravanti** [comment]
@lis2 Well, since August and September has come and gone, are you still all good to do the October meetup?

**Comment by paulfioravanti** [comment]
Hey @lis2 , thanks for speaking last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and if you create a Twitter account in the meantime, tweet the slides link out to `@rorosyd`, and we'll give it a retweet. Otherwise, if you want to make the materials public and share them, let us know by a link or something that we'll tweet that out!
