### ISSUE TITLE
Exercism Exercise - Sum of Multiples

### ISSUE THREAD

**Issue by hamlees93** [rails-oceania/roro#191]
I'd like to present [my solution](https://exercism.io/my/solutions/b11efb24c4ee4ffbabb06aa586512f0f) to this month's exercism - 'sum of multiples'.

Intended audience - Beginners
Ready - Immediately 
5m lightning talk

**Comment by RocketRobC** [comment]
Hi,

That's awesome, thanks!.

Would you be able to provide a little more information about yourself and
I'll add you to the lineup.

**Comment by hamlees93** [comment]
Sure thing. I'm very new to programming - having only started a course with Coder Academy in the middle of August. Before deciding to do the course, I barely knew how to turn a computer on, but with a couple of small online courses, and 7 weeks of fulltime study, I'm slowly getting there.

Let me know if theres anything else you'd like

**Comment by hamlees93** [comment]
I am still yet to get on twitter - on my to-do list, but here is a photo of me that can be used 

![git](https://user-images.githubusercontent.com/33846980/46566307-5cc09080-c95f-11e8-9de9-707c3a020cfc.jpg)

**Comment by paulfioravanti** [comment]
Hey @hamlees93 , thanks for speaking last night, and apologies for now being able to see it in person!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and if you create a Twitter account in the meantime, tweet the slides link out to `@rorosyd`, and we'll give it a retweet. Otherwise, if you want to make the materials public and share them, let us know by a link or something that we'll tweet that out!
