### ISSUE TITLE
Introduction to Hanami 

### ISSUE THREAD

**Issue by sinogermany** [rails-oceania/roro#198]
@paulfioravanti  I can give a talk about Hanami #158 . 

# Introduction to Hanami 

---

## Agenda

- Thinking from the basis
  - What on earth is a framework?
  - What on earth is a web framework?
  - What on earth is an MVC framework?

- FAQ when designing an Information Management System
  - What kind of information are we dealing with? (business use cases)
  - Where does all the information live? (DB, REST, SOAP, Files, Memory)
  - How to retrieve / store the information from the app? (ActiveRecord / Repository)
  - How to translate the retrieved information into business concepts? (ActiveRecord / Model)
  - How to output the information from the system? (console, sound, http, tcp, udp etc.)
  - How to present the information to the users / consumers? (html, json, yml, xml, protobuf, thrift etc.)
  - How do we accept user input? (http requests [form POST, json POST etc.], RPC calls, websocket etc.)

- Main components of Rails 

- Main components of Hanami

- Tools
  - `active_support`
  - `dry-xxx` library
  - rails-specific gems

- Demo (Rails vs Hanami)

---

## Other info

- Intended audience - intermediate knowledge of ruby language, basic knowledge of rails
- Month: Dec 2018
- Length of talk: full-length talk 
- Your Twitter username: I don't tweet unfortunately...
- avatar: https://www.linkedin.com/in/daniel-deng-aa72313b/

## About me

- Daniel Deng
- Senior Data Engineer @ Airtasker
- Polyglot dev with some ruby experience  #:)

**Comment by paulfioravanti** [comment]
Hey Daniel, thanks for the submission!

Since you asked for comments and suggestions, I have some! :)

That's quite a detailed agenda! Do you think you'll be able to cover it all in 15 minutes?

Please feel free to correct me, but I would almost wager that your agenda content contains two separate talks: one about web frameworks in general (content under the "Thinking from the basis" and "FAQ when designing an Information Management System" headings), and one about comparing and contrasting the differences between Rails and Hanami (the rest of the headings).

When I submitted #158 , it was to see a talk more about the latter, with the assumption that the audience is somewhat familiar with Rails and the concepts that it popularised (like MVC etc), and a focus on what's different in Hanami, why it's good and worth using, and a discussion on whether it is worth choosing over Rails if I was going to choose to write a new web application in Ruby (or what kind of application would Hanami be suited for). Basically, sell me Hanami as a developer :)

Don't let my opinions dissuade you from talking about web frameworks in general, though, if that's more of the kind of talk content you wanted to do (or covering the entirety of your agenda in your talk if you believe you can cover it in 15 minutes).  Anyway, though, what do you think?

**Comment by paulfioravanti** [comment]
Totally valid points on your side as well! Giving a brief background on web frameworks before launching into Hanami sounds good to me 👍 Let's lock you in for December! I'm looking forward to seeing what you come up with!

**Comment by paulfioravanti** [comment]
Hey @sinogermany, thanks for speaking tonight!

When you have a few moments, could you please export your slides to PDF, put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and put a link to them here in the issue and we'll tweet the slides link out on the `@rorosyd` account.
