### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by langsharpe** [rails-oceania/roro#281]
- How to use timezones to make your application more useful
- Common patterns in Rails applications
- I'm open to suggestions on what part or angle people would find interesting

Length: About 10 minutes.
When: November or December meetup.
Twitter: @LangSharpe
Photo: https://en.gravatar.com/userimage/11228629/c6bf6077fa14b4d68f7bf00ae461cf67.png

**Comment by mathewdbutton** [comment]
Hey @langsharpe! 

Thank you for volunteering to talk at ROROSyd, we really appreciate it. This sounds great, I'm looking forward to hearing about timezones (because personally they make my head hurt)

You are locked in for the 8th of December Meetup.

If you're around for November's meetup perhaps we can put the word out there on the call to see if people have any other things they'd like to hear about. 

I suspect you might cover most of these in the points you've raised, but for a timezone novice myself, I'd be interested in things like:
- At what stage of a project should I start thinking about adding in timezones
- How might I add timezones to an existing project that's not really cared about timezones.
- Which date/time/datetime class and methods should I be using to ensure I don't have a bad timezone time.
They may not quite what you were thinking so please feel free to disregard.

**Comment by hhemanth** [comment]
@langsharpe  You are confirmed for December. Just confirming with you again.

**Comment by langsharpe** [comment]
Thanks @hhemanth . Yes I'll be ready for the 8th of December.

**Comment by mathewdbutton** [comment]
Thanks so much for speaking on Tuesday @langsharpe, I'm gutted I wasn't able to see it, I heard it went well. Are you okay with us uploading the recording of your presentation to Youtube?

**Comment by langsharpe** [comment]
That would be great. A bit nervous to listen back to it, but it will be interesting.
