### ISSUE TITLE
Bulletproof Your Code: Concurrency and Idempotence

### ISSUE THREAD

**Issue by the-dina** [rails-oceania/roro#342]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
We will examine the issues that can arise when concurrency checks are overlooked, and explore various solutions to address these challenges. Additionally, we will discuss how to ensure that our scripts and data migrations are safe to run multiple times by implementing idempotence.
- Which month's meetup you would like to present at
Oct, Nov
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
25
- Your Twitter username (if you have one)
Not a fan of Elon Musk 😉 
- Are you happy to have your talk published on the RubyAU YouTube channel?
Yes, of course
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
My github profile picture is pretty fine 😊

**Comment by Yasmin-A95** [comment]
Hi @the-dina, we'd love to have you speak at our [November 14 meetup](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/296245671/) if you're available as we have a few speakers already lined up for October. Let me know if that suits you. As always feel free to reach out to me or any of the other organisers if you have any questions or concerns :)

**Comment by the-dina** [comment]
Hey @Yasmin-A95 , thanks and that sounds great! let's have mine for the November meetup. 😊

**Comment by Yasmin-A95** [comment]
Perfect, as always feel free to reach out to me or any of the other organisers if you need anything.

**Comment by the-dina** [comment]
Awesome! see you there Yasmin

**Comment by cheddachedda** [comment]
Hey @the-dina great to have you speaking again!

Just checking in with some questions:
1. Just checking that you're aware that we'll be at a new venue, Microsoft Reactor 10/11 York St Sydney.
2. Do you know what app you're using for your slides yet? (Google Slides? Canva? Keynote?) We tested it out the other day at the new venue, and anything should be fine with a two-screen setup. I just want to be proactive because we've had issues in the past with presenters not being able to see their speaker notes.
3. And finally, could we ask that we keep to a 20min time limit? We want to keep it flowing and engaging ☺️

**Comment by the-dina** [comment]
Hey @cheddachedda , thanks a lot, it's my honour doing it.

About:
1. Good thinking and thanks a heap for reminding.
2. I will use Google Slides.
3. And capping it to 20 minutes is a fab idea. Let's do it.

Have a nice Friday and weekend ahead,
Dina
